name: Other Issue
description: Template for blank issues
body:
  type: input
  attributes:
    label: Description
    description: >
      Describe your question or issue in detail and be sure to include
      enough context to make your inquiry easily understandable.
  validations:
    required: true
