name: Echo Input
description: Print the input passed to this action
inputs:
  input:
    description: Input string
    required: true
  json:
    description: JSON-encoded string
outputs:
  output:
    description: The input string
  outputRaw:
    description: Raw input string
  json:
    description: JSON-encoded input string
  jsonParsed:
    description: JSON-decoded input string
runs:
  using: node12
  main: dist/index.js
