name: Background Tasks

on:
  push:
    branches:
      - main
    paths:
      - server.bat

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start server in background
        run: |
          cmd /c "START /b server.bat"
          # Need to sleep for a bit here so that the Python server can boostrap
          sleep 2
          curl -X GET "http://localhost:9195/files/plain.txt"
