name: Get check_run_id

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wait: [1, 2]
    steps:
      - name: Fake build process
        run: |
          sleep ${{ matrix.wait }}
  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: query-jobs
        with:
          script: |
            const result = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });
            console.log(result);
            return result.data.jobs.map(job => `${{ github.event.pull_request._links.html.href }}/checks?check_run_id=${ job.id }`).join("\n");
      - name: Print fetched jobs
        env:
          JOBS_DATA: ${{ steps.query-jobs.outputs.result }}
        run: |
          echo "$JOBS_DATA"
