name: Get check_run_id

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wait: [2, 3]
    steps:
      - name: Fake build process
        run: |
          sleep ${{ matrix.wait }}
  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: query-jobs
        with:
          script: |
            const data = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });
            console.log(`status: ${ data.status }`);
            return data.jobs
      - name: Print fetched jobs
        env:
          JOBS_DATA: ${{ steps.query-jobs.outputs.result }}
        run: |
          echo "$JOBS_DATA"
      - run: |
          #echo "${{ format('{0}/checks?check_run_id={1}', github.event.pull_request._links.html.href, steps.query-jobs.outputs.result) }}"
