name: Get check_run_id

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wait: [1, 2]
    steps:
      - name: Fake build process
        run: |
          sleep ${{ matrix.wait }}
  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: query-jobs
        with:
          script: |
            const result = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });
            console.log(result);
            return result.data.jobs[result.data.jobs.length-1].id;
      - name: Print fetched job ID
        env:
          JOB_ID: ${{ steps.query-jobs.outputs.result }}
        run: |
          echo "$JOB_ID"
      - name: Print check link
        run: |
          echo '${{ format('{0}/checks?check_run_id={1}', github.event.pull_request._links.html.href, steps.query-jobs.outputs.result) }}'
