name: Command Echoing

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: No echoing
        id: no-echo
        run: |
          cd ..
          pwd
          ls -lah
          curl http://www.example.org | grep "illu"
          echo "::set-output name=action_fruit::strawberry"
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "::group::My title"
          echo "Inside group"
          echo "::endgroup::"
          echo "::add-mask::Mona The Octocat"
          echo "::stop-commands::start-commands"
          echo "::set-output name=action_vegetable::carrot"
          echo "::start-commands::"
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "::add-matcher::eslint-compact-problem-matcher.json"   
          echo "::remove-matcher owner=eslint-compact::"
      - id: string1
        uses: ASzc/change-string-case-action@v1
        with:
          string: XyZzY
      - run: |
          echo ${{ steps.string1.outputs.lowercase }}
          echo ${{ steps.no-echo.outputs.action_fruit }}
          echo ${{ steps.no-echo.outputs.action_vegetable }}
          echo "$action_state"

      - name: Echoing on
        id: with-echo
        run: |
          echo "::echo::on"
          cd ..
          pwd
          ls -lah
          curl http://www.example.org | grep "illu"
          echo "::set-output name=action_fruit::apple"
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "::group::Another title"
          echo "Inside group"
          echo "::endgroup::"
          echo "::add-mask::Heinz Ketchup"
          echo "::stop-commands::start-commands"
          echo "::set-output name=action_vegetable::potato"
          echo "::start-commands::"
          echo "action_state=green" >> $GITHUB_ENV
          echo "::add-matcher::eslint-compact-problem-matcher.json"   
          echo "::remove-matcher owner=eslint-compact::"
      - id: string2
        uses: ASzc/change-string-case-action@v1
        with:
          string: XyZzY
      - run: |
          echo "::echo::on"
          echo ${{ steps.string2.outputs.lowercase }}
          echo ${{ steps.with-echo.outputs.action_fruit }}
          echo ${{ steps.with-echo.outputs.action_vegetable }}
          echo "$action_state"
