name: Echo Input

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/echo-input
        id: echo
        with:
          input: " "
      - env:
          OUTPUT: ${{ steps.echo.outputs.output }}
          TOJSON: ${{ toJSON(steps.echo.outputs.output) }}
          JSON: ${{ steps.echo.outputs.json }}
        run: |
          echo "Output: $OUTPUT"
          echo "toJSON: $TOJSON"
          echo "JSON: $JSON"
