name: Echo Input

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/echo-input
        id: echo
        with:
          input: |
            Does the whitespace
             		survive?    
      - run: |
          echo "Output: ${{ steps.echo.outputs.output }}"
          echo "JSON: ${{ steps.echo.outputs.json }}"
