name: Labeling

on:
  pull_request:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages
        env:
          COMMIT_MSGS: ${{ toJSON(github.event.commits.*.message) }}
        run: |
          echo "$COMMIT_MSGS"
        
