name: Overwrite env

on: workflow_dispatch

jobs:
  job1:
    runs-on: windows-latest
    env:
      GENERATOR_PLATFORM: initial value

    steps:
      - name: windows-dependencies
        run: |
          $generator= "-DCMAKE_GENERATOR_PLATFORM=x64"
          $foo= "bar"
          echo "Generator: ${generator}"
          echo "foo: ${foo}"
          echo "GENERATOR_PLATFORM=$generator" >> $GITHUB_ENV
          echo "OTHER_NAME=$foo" >> $GITHUB_ENV

      - name: Bash
        shell: bash
        run: |
          echo "env.GENERATOR_PLATFORM = ${{ env.GENERATOR_PLATFORM }}"
          echo "env.OTHER_NAME = ${{ env.OTHER_NAME }}"
          echo "GENERATOR_PLATFORM = $GENERATOR_PLATFORM"
          echo "OTHER_NAME = $OTHER_NAME"

      - name: PowerShell
        shell: pwsh
        run: |
          echo "env.GENERATOR_PLATFORM = ${{ env.GENERATOR_PLATFORM }}"
          echo "env.OTHER_NAME = ${{ env.OTHER_NAME }}"
          echo "GENERATOR_PLATFORM = $Env:GENERATOR_PLATFORM"
          echo "OTHER_NAME = $Env:OTHER_NAME"
