name: Trigger info

on:
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        env:
          GITHUB: ${{ toJSON(github) }}
          PR: ${{ toJSON(!!github.event.issue.pull_request) }}
        run: |
          echo "on: ${{ github.event_name }}"
          echo "type: ${{ github.event[github.event_name].action }}"
          echo "PR? $PR"
          echo "github: $GITHUB"
          cat "${{ github.event_path }}"
